# Generated by Django 4.1.5 on 2023-01-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cep',
            field=models.PositiveIntegerField(blank=True, help_text='Insira o seu CEP.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cidade',
            field=models.CharField(blank=True, help_text='Insira a sua cidade.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='endereco',
            field=models.CharField(blank=True, help_text='Insira o seu endereço.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='estado',
            field=models.CharField(blank=True, help_text='Insira o seu estado.', max_length=100, null=True),
        ),
    ]
