# Generated by Django 4.1.5 on 2023-01-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_user_cep_alter_user_cidade_alter_user_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cep',
            field=models.CharField(blank=True, help_text='Insira o seu CEP.', max_length=8, null=True),
        ),
    ]
