# Generated by Django 4.1.5 on 2023-02-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_user_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bairro',
            field=models.CharField(blank=True, help_text='Insira o seu bairro.', max_length=100, null=True),
        ),
    ]
