# Generated by Django 4.1.5 on 2023-04-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='detalhes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
