# Generated by Django 4.1.5 on 2023-01-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='complete',
            field=models.BooleanField(db_column='Pedido Completado', default=False, null=True),
        ),
    ]
