# Generated by Django 4.1.5 on 2023-02-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_ecommerce', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enderecoenvio',
            options={'verbose_name': 'endereço enviado', 'verbose_name_plural': 'endereços enviados'},
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=200, null=True, verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Preço (R$)'),
        ),
    ]
