# Generated by Django 4.1.5 on 2023-02-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_ecommerce', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateTimeField(auto_now=True, verbose_name='Data do pedido'),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='data_adicao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
