# Generated by Django 4.1.5 on 2023-04-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_ecommerce', '0003_alter_enderecoenvio_options_alter_produto_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='detalhes',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
