# Generated by Django 4.1.5 on 2023-01-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_ecommerce', '0003_alter_pedido_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos'),
        ),
    ]
