# Generated by Django 4.1.5 on 2023-02-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_ecommerce', '0003_alter_pedido_data_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enderecoenvio',
            name='bairro',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
