# Generated by Django 4.1.5 on 2023-04-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_ecommerce', '0004_produto_detalhes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='detalhes',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Produto'),
        ),
    ]
