# Generated by Django 4.1.5 on 2023-01-28 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_ecommerce', '0006_alter_produto_preco'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidoitem',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Itens'},
        ),
        migrations.AlterField(
            model_name='enderecoenvio',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Pedido foi Completado'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data do pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id_transacao',
            field=models.CharField(max_length=100, verbose_name='Código da Transação'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
